services:
  - type: web
    name: repopulse
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/src/.cache/puppeteer
      - key: VITE_GITHUB_TOKEN
        sync: false
